name: Taric
version: '${version}'
main: org.aincraft.TaricBootstrap
api-version: '1.21'
authors: [ mintychochip ]
commands:
  gem:
    description: creates a gem
  container:
    description: checks container



